name: First Cron Job

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 *  * * *'

permissions:
  contents: write
  
jobs:
  cron:
      name: Deployment
      uses: ./.github/workflows/deploy.yml
  
  Workflow_dsiable:    
  
   runs-on: ubuntu-latest
   needs: cron
   
   steps:
   
     - name: CheckOut SourceCode
       uses: actions/checkout@v3
       
     - name: Disabling workflow
       run: gh workflow disable "cronjob.yml"
       env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
