name: Print some text every 3rd minute
on:
  schedule:
    - cron: '*/3 * * * *'

jobs:
  print_text:
    runs-on: ubuntu-latest
    steps:
      - name: Print some text
        run: echo Periodically printing passages
