name: Deploy

on:
 workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Run a one-line script
       run: echo Hello, world!
       
     - name: Disabling workflow
       run: gh workflow disable "cronjob.yml"
       env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
