name: .NET Build

on:
  workflow_dispatch:
  
jobs:

  Pre-Release:
  
      name: Versioning
      runs-on: ubuntu-latest
      
      outputs:
        version: ${{ steps.versionid.outputs.version }}
        
      steps:
        - uses: actions/checkout@v2

        - id: versionid
          run: |
            echo setting release version!!
            echo "${{ github.run_number }}" >> version.cfg
            newversion=$(cat version.cfg | tr -d "[:space:]")
            echo $newversion
            echo "::set-output name=version::$newversion"
            
  Build:
    
    needs: Pre-Release
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Authenticate to GitHub Actions
      run: dotnet nuget add source --username shiyamsundark --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/shiyamsundark/index.json"
    
    - name: Pack Package
      run: |
       echo ${{needs.Pre-Release.outputs.version}}
       dotnet pack --configuration Release -p:PackageVersion=${{needs.Pre-Release.outputs.version}}
    
    - name: Publish Package
      run: |
        dotnet nuget push "bin/Release/*.nupkg" --source "github"



     
 
 
