name: CD STAGE

on:
  workflow_dispatch:
   inputs:
      Deploy:
        type: boolean
        description: Check this to Deploy at non-business Hours

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  STG_Deploy_Approval:
   runs-on: ubuntu-latest
   needs: build
   environment: STG
   steps:
   
    - name: CheckOut SourceCode
      uses: actions/checkout@v3
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           
    - name: Scheduling Deployment
      run: |
           if [[ ${{ github.event.inputs.Deploy }} == 'true' ]];then
             echo Enabling cronjob for deployment!! 
             gh workflow enable "cronjob.yml" 
           else
             echo Please check the checkbox to continue with the deployment!!
             echo Failing due to missing condition..
             exit 1
           fi
