name: STG test approval

on:
  workflow_dispatch:
 
jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  STG_Deploy_Approval_IT_Team:
   runs-on: ubuntu-latest
   needs: build
   environment: STG
   steps:
   
      - name: IT Team's Approval
        run: echo Approved from IT team
        
  STG_Deploy_Approval_Devops_Team:
   runs-on: ubuntu-latest
   needs: [build,STG_Deploy_Approval_IT_Team]
   environment: Devops
   steps:
   
      - name: Devops Team's Approval
        run: echo Approved from Devops team

